title: NIME
email: website@nime.org
description: >-
  The International Conference on New Interfaces for Musical Expression
  gathers researchers and musicians from all over the world to share their
  knowledge and late-breaking work on new musical interface design.
baseurl: ""
url: "https://nime.org" 

encoding: utf-8 
lang: en-GB 
logo: "/assets/logos/nime.png"
css_inline: true

markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed
permalink: pretty 
excerpt_separator: <!-- more -->
timezone: Europe/London

plugins:
  - jekyll-mentions
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-gist
  - jekyll-datapage-generator
  - jekyll-toc

# This is the page_gen plugin config
# This creates individual pages for each bibliography entry.
page_gen:
- data: nime_papers
  template: paper
  dir: proc
  index_files: true # false # I think this makes directories for each one which breaks linking somehow.
  name: ID
  title: title
  extension: html 
  page_data_prefix: entry
  debug: true 
- data: nime_music
  template: paper
  dir: proc_music
  index_files: true # false # I think this makes directories for each one which breaks linking somehow.
  name: ID
  title: title
  extension: html 
  page_data_prefix: entry
  debug: true 
- data: nime_installations
  template: paper
  dir: proc_installations
  index_files: true # false # I think this makes directories for each one which breaks linking somehow.
  name: ID
  title: title
  extension: html 
  page_data_prefix: entry
  debug: true 

scholar:
  style: "/assets/acm-sigchi-proceedings.csl"
  repository: preprints
  bibliography_template: bibliography
  # details_layout: detail_layout
  bibliography: nime_papers
  group_by: year
  group_order: descending
  bibliography_list_tag: "ul"
  bibliography_item_tag: "li"

jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: nimeconf # jekyll-seo-tag > Owners twitter username
author: NIMEconference # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: NIME Conference # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/nimeconf
    - https://github.com/NIMEconference

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/nimeconf
  GitHub: https://github.com/NIMEconference
  link: http://nime.org
  RSS: /feed.xml
    
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/

include:
- _redirects

navigation_header:
- title: Home
  url: /
- title: Past NIMEs
  url: /past-nimes/
- title: Proceedings
  url: /archives/
- title: Music
  url: /music/
- title: Hosting
  url: /hosting/
- title: Committee
  url: /committee/
- title: Mailing List
  url: /list/
- title: Statements
  url: /statements/
- title: Forum
  url: https://forum.nime.org/
- title: Mentorship
  url: /mentorship/

navigation_footer:
- title: Back to top
  url: "#top"

collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "News from the NIME world" # The post list page content
    feature_image: "/assets/headers/nime2010-ultrasonic.jpg"
    feature_text: ""
