title: NIME
email: website@nime.org
description: >- # this means to ignore newlines until "baseurl:"
  The International Conference on New Interfaces for Musical Expression
  gathers researchers and musicians from all over the world to share their
  knowledge and late-breaking work on new musical interface design.
baseurl: ""
url: "https://nime.org" 

encoding: utf-8 
lang: en-GB 
logo: "/assets/logos/nime.png"
css_inline: true

sass:
  style: compressed
permalink: pretty 
excerpt_separator: <!-- more -->
timezone: Europe/London

markdown: kramdown
theme: alembic-jekyll-theme
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-datapage-generator

page_gen:
- data: nime_papers
  template: paper
  dir: proc
  index_files: true
  name: ID
  title: title
  extension: html 
  debug: true 

scholar:
  style: "/assets/acm-sigchi-proceedings.csl"
  repository: preprints
  bibliography_template: bibliography
  # details_layout: detail_layout
  bibliography: nime_papers
  group_by: year
  group_order: descending
  bibliography_list_tag: "ul"
  bibliography_item_tag: "li"

jekyll-mentions: https://twitter.com # jekyll-mentions > service used when @replying
twitter:
  username: nimeconf # jekyll-seo-tag > Owners twitter username
author: NIMEconference # jekyll-seo-tag > default author
social: # jekyll-seo-tag > social overrides
  name: NIME Conference # jekyll-seo-tag > real name
  links:  # jekyll-seo-tag > social aliases (sameAs)
    - https://twitter.com/nimeconf
    - https://github.com/NIMEconference

social_links: # Appears in sidebar. Set the urls then uncomment and comment out as desired
  Twitter: https://twitter.com/nimeconf
  GitHub: https://github.com/NIMEconference
  link: http://nime.org
  RSS: /feed.xml
    
exclude:
- README.md
- Gemfile
- Gemfile.lock
- node_modules
- vendor/bundle/
- vendor/cache/
- vendor/gems/
- vendor/ruby/

include:
- _redirects

navigation_header:
- title: Home
  url: /
- title: Past NIMEs
  url: /past-nimes/
- title: Proceedings
  url: /archives/
- title: Music
  url: /music/
- title: Hosting
  url: /hosting/
- title: Committee
  url: /committee/
- title: Mailing List
  url: /list/
- title: Statements
  url: /statements/
- title: Forum
  url: https://forum.nime.org/

navigation_footer:
- title: Back to top
  url: "#top"

collections:
  posts:
    title: Posts # Needed for Siteleaf
    output: true
    description: "News from the NIME world" # The post list page content
    feature_image: "/assets/headers/nime2010-ultrasonic.jpg"
    feature_text: ""

# sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
#   Twitter: "#0d94e7"
#   facebook: "#3B5998"
#   Email: true
