#!/usr/bin/env python3
"""List the hand-uploaded files under /proceedings/ as a manifest for the site checks.

The proceedings PDFs live only on the server, so the build can't see them. Run
this after uploading or replacing anything in /proceedings/, commit the result,
and scripts/check_site_quality.py will check the bibliography against it.

On a local copy of the web root:

    python3 scripts/make_pdf_manifest.py /path/to/webroot -o _data/pdf_manifest.yml

Or directly on the server (uses only the standard library, nothing to install):

    ssh -p 65002 user@server 'python3 - public_html' \\
        < scripts/make_pdf_manifest.py > _data/pdf_manifest.yml

Output is YAML with one line per file, keyed by its path relative to the web
root, e.g. "proceedings/2026/nime2026_1.pdf": {bytes: 123, sha256: "..."}.
Dotfiles and dot-directories are skipped.
"""
import argparse
import datetime
import hashlib
import json
import os
import sys


def sha256(path):
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for block in iter(lambda: f.read(1 << 20), b""):
            h.update(block)
    return h.hexdigest()


def scan(webroot, subdir="proceedings"):
    """Return {relative path: {"bytes": n, "sha256": hex}} for every file under webroot/subdir."""
    files = {}
    top = os.path.join(webroot, subdir)
    if not os.path.isdir(top):
        raise SystemExit(f"no such directory: {top}")
    for dirpath, dirnames, filenames in os.walk(top):
        dirnames[:] = sorted(d for d in dirnames if not d.startswith("."))
        for name in sorted(filenames):
            if name.startswith("."):
                continue
            path = os.path.join(dirpath, name)
            if not os.path.isfile(path):
                continue
            key = os.path.relpath(path, webroot).replace(os.sep, "/")
            files[key] = {"bytes": os.path.getsize(path), "sha256": sha256(path)}
    return files


def to_yaml(files, generated):
    # Written by hand rather than with PyYAML so this runs on the server as-is.
    # JSON strings are valid YAML double-quoted scalars, so keys are safely quoted.
    lines = [
        "# Generated by scripts/make_pdf_manifest.py. Do not edit by hand;",
        "# regenerate after every upload or replacement in /proceedings/.",
        f"generated: {json.dumps(generated)}",
        f"count: {len(files)}",
        "files:",
    ]
    for key in sorted(files):
        f = files[key]
        lines.append(f"  {json.dumps(key)}: {{bytes: {f['bytes']}, sha256: {json.dumps(f['sha256'])}}}")
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description="List the files under /proceedings/ as a manifest.")
    ap.add_argument("webroot", help="the web root that contains proceedings/ (e.g. public_html)")
    ap.add_argument("--subdir", default="proceedings", help="folder under the web root to list")
    ap.add_argument("-o", "--output", help="write here instead of stdout")
    args = ap.parse_args()

    generated = datetime.datetime.now(datetime.timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    text = to_yaml(scan(args.webroot, args.subdir), generated)
    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(text)
    else:
        sys.stdout.write(text)


if __name__ == "__main__":
    main()
