name: Build Jekyll site and deploy via rsync
on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: build
        run: |
          bundle exec jekyll build
      - name: set up known_hosts
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/known_hosts
          ssh-keyscan -p 65002 -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts
      - name: set up private key
        run: |
          eval $(ssh-agent)
          echo "${{ secrets.SSH_PRIVATE_KEY }}" >> ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add
      - name: rsync # deploys to shared hosting server using rsync
        run: |
          rsync \
          -rvz \
          -e 'ssh -p 65002 -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa -i ~/.ssh/id_rsa' \
          --progress \
          --iconv=utf8,iso88591 \
          _site/ \
          ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:public_html/
      # - name: Deploy 🚀
      #   uses: JamesIves/github-pages-deploy-action@v4.2.5
      #   with:
      #     branch: gh-pages # The branch the action should deploy to.
      #     folder: _site # The folder the action should deploy.
