name: Build and deploy Jekyll site to GitHub Pages

on:
  push:
    branches:
      - master

jobs:
  github-pages:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.1
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: build
        run: |
          bundle exec jekyll build --baseurl nime
      - name: rsync
        run: |
          rsync \
	          -rvz \
	          -e \
	          'ssh -p 21098 -o HostKeyAlgorithms=+ssh-rsa -o PubkeyAcceptedAlgorithms=+ssh-rsa' \
	          --progress \
	          _site/ \
	          ${{ secrets.SERVER_USERNAME }}@${{ secrets.SERVER_IP }}:public_html/nime/
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: _site # The folder the action should deploy.
